### ISSUE TITLE
Collecting for next weekly

### ISSUE THREAD

**Issue by jbenet** [ipfs/roundups#24]

**Comment by bergie** [comment]
USB dead drop over IPFS https://github.com/c-base/ipfs-deaddrop

the device where we run the IPFS node https://www.flickr.com/photos/bergie/24769765569/in/datetaken-public/ and the view you get when you plug in a USB stick and it has been pinned https://www.flickr.com/photos/bergie/24857415123/in/datetaken-public/

Update:
Welcome screen https://www.flickr.com/photos/bergie/24995390484/in/datetaken-public/
Progress bar https://www.flickr.com/photos/bergie/25600254946/in/datetaken-public/
Result screen: https://www.flickr.com/photos/bergie/25330279580/in/datetaken-public/

Short blog post: https://github.com/the-domains/bergie-c-base/blob/master/_posts/2016-03-09-usb-dead-drop-publishing-via-ipfs.md

**Comment by RichardLitt** [comment]
Thanks @bergie!

**Comment by ibnesayeed** [comment]
> At [Archives Unleashed](https://artsweb.uwaterloo.ca/archivesunleashed/), a Web Archive Hackathon in Toronto, [Mat Kelly](https://twitter.com/machawk1) and a few others made an "Interplanetary Wayback Machine", a distributed and persistent archive replay system using IPFS. The rough but functional code can be seen [here](https://github.com/oduwsdl/toronto).

Hi @RichardLitt I would suggest a few changes in the week 6 update:
- We were only two people working on this project, so mentioning both names instead of "a few others" would be better.
- We didn't add the term "Machine" in its name, so it should be removed from the title and the body.
- We have renamed the repository, so the link can be updated (although GH is redirecting it).
- We are still planning to work on it further, so the code might not be that rough going forward.

Here is how the changed update might look:

---

#### Interplanetary Wayback (IPWB)

At [Archives Unleashed](https://artsweb.uwaterloo.ca/archivesunleashed/), a Web Archive Hackathon in Toronto, [Mat Kelly](https://twitter.com/machawk1) (@machawk1) and [Sawood Alam](https://twitter.com/ibnesayeed) (@ibnesayeed) from [ODU WSDL Research Group](https://github.com/oduwsdl) developed an IPFS based distributed and persistent archive replay system called [Interplanetary Wayback](https://github.com/oduwsdl/ipwb).

---

**Comment by RichardLitt** [comment]
@ibnesayeed Thanks so much for pointing that out. We should have fact checked it a bit better. Also, thanks for making it! :D 

I've edited it on ipfs/ipfs#151, PRed the website, and edited it here. If you like, I could also print the above in the next weekly, too, as a note saying that here is the more factual information?

**Comment by ibnesayeed** [comment]
Thanks @RichardLitt for taking time. I think these weekly updates are very helpful and playing an important role in the keeping the community aware of what's going on. I certainly won't mind a bit of more visibility by yet another mention in the next week's update, but that is not mandatory. However, there is a space before the last full stop in the update which might hurt some people with OCD. ;-)

Additionally, we are working on a conference paper about IPWB, which may appear in a weekly update later if the paper is ready on time and gets accepted.

**Comment by RichardLitt** [comment]
@ibnesayeed Thank _you_ for taking the time. :) 

Let's wait until the paper - I look forward to announcing that. :+1: Good luck!
