### ISSUE TITLE
Collection for IPFS Weekly 7 (March 7th--March 14th)

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#27]

**Comment by bergie** [comment]
https://github.com/the-grid/jsjob-ethereum is an experiment at creating a computational market on top of Ethereum. Computational jobs are run in a JavaScript sandbox, and both input data, the algorithm to run, and the produced results are shared over IPFS.

**Comment by bergie** [comment]
https://github.com/c-base/ipfs-ringpin is a set of tools for setting up an IPFS "file pinning ring" between multiple parties. Can be used for example for hackerspaces to provide redundancy by pinning each other's files.

**Comment by ghost** [comment]
I don't have anything good for the weekly right now -- would have to put lipstick on the pig :)

**Comment by daviddias** [comment]
- multiaddr JS impl was upgraded, now it matches go-ipfs features which means protocols whose code's required a varint https://github.com/jbenet/js-multiaddr
- mafmt now does uTP and WebSockets validation as well
- new libp2p-swarm released, check it out :)

**Comment by whyrusleeping** [comment]
A nasty bug in our networking code was fixed this week. An issue in yamux (our primary stream multiplexer) would cause code to hang when opening a new stream if there were too many in flight stream opens. As a result of this, large file transfers (`ipfs refs -r`, `ipfs get`, and so on) would hang.

IPFS 0.4.0 is now very close to shipping, we ran @dignifiedquire's [randor](https://github.com/dignifiedquire/randor) tool quite extensively and are more confident in the repo operations that have changed since 0.3.11. The release now has a [somewhat short checklist of things](https://github.com/ipfs/go-ipfs/issues/2334#issuecomment-195046511) that are blocking the official release.

As a small side project, I started benchmarking each of our possible datastore implementations with [ds-bench](https://github.com/whyrusleeping/ds-bench). The results will help us improve the performance of our storage moving forward. On that same topic, I started an experiment in new and exciting datastores and wrote a [datastore implementation](https://github.com/whyrusleeping/sql-datastore) that can be backed by a sql database. I then spun up a postgresql database (from docker) and ran the benchmarks against it, without any sort of tuning the [initial performance metrics](https://gist.github.com/whyrusleeping/55e2759dfa4b5b60a2cf) showed that it was around three time as fast as our current on-disk datastore. (Note: the metrics are simply testing the performance of writing random 256k binary blobs to each datastore).

**Comment by daviddias** [comment]
IPLD discussion https://www.youtube.com/watch?v=QVfL0VrvBww

**Comment by haadcode** [comment]
[Orbit ](https://github.com/haadcode/orbit) is back in active development and going through a major code base overhaul. It now uses orbit-db as it's database layer.

[orbit-db](https://github.com/haadcode/orbit-db) is a KV-store and Event Log on top of IPFS which allows developers to use IPFS as a database. Last week orbit-db got big performance and stability improvements and is now using CRDTs for eventual consistency.
