### ISSUE TITLE
[RFC] IPFS Weekly – A celebratory recap of 2018 for first letter of 2019

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#70]
The IPFS Newsletter is taking a break over the next two weeks, since Christmas Day and New Years Day both fall on the typical publication date: Tuesdays.

When the IPFS Newsletter returns on January 8, I would love to start 2019 with a look back at all that the IPFS community has accomplished in 2018, and possibly a sneak peek at what’s in store for 2019.

To do this, I definitely need your suggestions, memorable ships, releases, PRs, commits, talks, tutorials – anything the community has considered a win. 

I’m going to cross-post this in [discuss.ipfs.io](https://discuss.ipfs.io/) to get direct feedback from the community as well. 

Many thanks in advance for your time and/or suggestions! 🙏

**Comment by terichadbourne** [comment]
@renrutnnej I expect to have a ProtoSchool announcement that can be included. When do you need this confirmed to make the 1/8 publication?

**Comment by jennwrites** [comment]
@terichadbourne Ideally by EOD 1/7 but definitely by first thing of 1/8. Thanks!

**Comment by terichadbourne** [comment]
@renrutnnej Turns out I was reading my calendar wrong. :) 

The only thing that should be in the 1/7 newsletter about ProtoSchool is encouragement  to attend the IPFS Weekly Call on 1/14 for a demo.  I've updated the topic and description in @pkafei's [schedule of upcoming talks](https://docs.google.com/spreadsheets/d/1XRB2QsPzCPLPOErKvDZfOKK3CMohI9t_QKNdztYMlK0/edit?usp=sharing) for you to reference, since I believe she said you'll be publishing that schedule for January topics in the 1/7 newsletter anyway. Including my preso in that last will be sufficient for this edition.

The 14th will be our official public launch, so I'll provide you with more copy to make a bigger splash in that edition, hopefully snagging the headline if it hasn't yet been claimed. (Although the site is live, we're trying not to drive too much public traffic before then as we make some final tweaks for launch.)

Thanks!

**Comment by jennwrites** [comment]
Working actively on this issue in #71
